# Generated by Django 4.1.1 on 2024-12-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_laboratorio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(auto_now=True),
        ),
    ]
